Add api parsers and fix tests
starkinfra/core-clojure pull request #4
Opened 2024-08-16 21:15 UTC by leoKagohara-Stark

2024-08-21 16:27 UTC, danielterra-stark commented on test/core_clojure/rest_test.clj
>                      "5297659795472384"
não deixar chumbadin

2024-08-21 16:28 UTC, danielterra-stark requested changes, later dismissed

2024-08-21 16:28 UTC, danielterra-stark commented on test/core_clojure/rest_test.clj
>                     "5297659795472384"
não deixar chumbadin

2024-08-21 16:28 UTC, danielterra-stark commented on test/core_clojure/rest_test.clj
> +                           "5297659795472384"
não deixar chumbadin

2024-08-23 14:45 UTC, luistarkbank commented on CHANGELOG.md
> +## [0.1.1] - 2024-08-07
nao tem nada no changeLog ?? jk

2024-08-23 14:45 UTC, luistarkbank commented on src/core_clojure/utils/rest.clj
> +     {:status (:status @request) :content (transform-keys-to-kebab (json-to-map (:content @request)))}
o nome dessa função está padronizado com os outros sdks ??

2024-08-23 15:05 UTC, leoKagohara-Stark commented on src/core_clojure/utils/rest.clj
> +     {:status (:status @request) :content (transform-keys-to-kebab (json-to-map (:content @request)))}
O padrão é cast, mudei aqui

2024-08-23 19:52 UTC, luistarkbank approved these changes

2024-08-23 21:06 UTC, merged